version: '3'
services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
